const express = require("express");
const route = express.Router();
const productCtroller = require("./Controller/Category");
const userController = require("./Controller/User");
const { deletecartproduct } = require("./Controller/AddtoCart");
const cartController = require("./Controller/AddtoCart");
const { userSignup } = require("./Controller/User");
const FilterCtroller = require("./Controller/Filter");
const Productcontroller = require("./Controller/Product");
const { isvalidate, secure } = require("./Controller/Middleware");
const { OrderProducts, getorderproducts } = require("./Controller/Orders");
route.post("/usersignup", isvalidate, userSignup);
route.post("/userlogin", userController.userLogin);
route.post("/addproduct", productCtroller.createcategary);
route.get("/getcategory", productCtroller.getcategory);
route.post("/addtocart", secure, cartController.addtocart);
route.post("/getcart", secure, cartController.getcart);
route.post("/deletecartproduct", secure, deletecartproduct);
route.post("/getfilter/:slug", FilterCtroller.getfilter);
route.post("/product/:id", Productcontroller.getProductById);
route.post("/productorder", secure, OrderProducts);
route.get("/getorderproduct", secure, getorderproducts);
module.exports = route;
